Added Symphony
RadioPeeker/Radios pull request #5
Opened 2020-11-13 22:33 UTC by xxdjbobbyxx

### Submissions:

* [ Yes] Does your submission meet with our requirements?
* [ Yes] Is the JSON file formatted correctly?
* [ Yes] Have you checked to ensure there aren't other open [pull requests](../../../pulls) for the same update/change?

2020-11-14 19:08 UTC, DefectivenessYT commented
Stream and API seem to be offline @xxdjbobbyxx, re-request review when all of this is sorted.

2020-11-14 19:08 UTC, DefectivenessYT requested changes
ensure api and live link function before pr'ing

2020-11-14 19:37 UTC, xxdjbobbyxx commented
Fixed the new issues.

2020-11-14 19:38 UTC, DefectivenessYT requested changes
live link doesn't work?

2020-11-14 19:42 UTC, xxdjbobbyxx commented
Port defined and mount point now created

2020-11-14 19:43 UTC, DamonOnYT requested changes
Links should be HTTPS.

API will also be added to RSpy meaning api_url should be "external", I will update the PR when it is.

2020-11-14 19:46 UTC, xxdjbobbyxx commented
We dont have a SSL because its on port 90 and therefor the website wont work without it being on port 80 so feel free to remove this pull request if you do not want Symphony on

2020-11-14 19:49 UTC, DamonOnYT commented
@xxdjbobbyxx Do you not understand how web ports work? You are fowaring everything to port 80 where Cloudflare then has SSL on their end.

2020-11-14 19:51 UTC, xxdjbobbyxx commented
Not everything is going through cloudflare as thats what is breaking shit on my end

2020-11-14 19:58 UTC, DamonOnYT commented
@xxdjbobbyxx Issue SSL via Azuracast. Considering the site is also only in HTTPS, We will not be able to merge it until you can sort out SSL Certificates.

I will be able to sort out SSL for the API, as its passed through RadioSpy however the radio SSL will need to be sorted by you.

2020-11-14 19:59 UTC, DefectivenessYT commented
Your radio is now showing "service unavailable." if you fix this, i'll proxy the radio stream through me for SSL.

2020-11-14 20:05 UTC, xxdjbobbyxx commented
> Your radio is now showing "service unavailable." if you fix this, i'll proxy the radio stream through me for SSL.

its working fine for me

2020-11-15 15:33 UTC, DefectivenessYT commented
All URLs is now secure and functioning, waiting on @DamonOnYT to add to radiospy api, then @jackkelly-bayliss or @JackKellyBayliss will proceed to add to RadioPeeker

2020-11-15 15:39 UTC, DefectivenessYT approved these changes

2020-11-15 18:19 UTC, jackkelly-bayliss commented
@DamonOnYT Let me know once this has been added to RadioSpy and I'll approve on my end.

2020-11-15 21:35 UTC, DefectivenessYT commented
@jackkelly-bayliss symphony has been added to the radiospy api 👍

2020-11-15 21:39 UTC, HexDevv requested changes
Consider moving away from a .tk domain. People are able to 'out-buy' it afaik.

2020-11-15 21:39 UTC, HexDevv commented on radios/S/symphonyradio/radio.json
> +        "logo": "https://symphonyradio.tk/assets/img/logo.png",
Consider moving away from a .tk domain. People are able to 'out-buy' it afaik.

2020-11-15 21:39 UTC, HexDevv commented on radios/S/symphonyradio/radio.json
> +        "website": "https://symphonyradio.tk",
Consider moving away from a .tk domain. People are able to 'out-buy' it afaik.

2020-11-15 21:39 UTC, HexDevv commented on radios/S/symphonyradio/radio.json
> +        "api_url": "https://api.symphonyradio.tk",
Consider moving away from a .tk domain. People are able to 'out-buy' it afaik.

2020-11-15 21:41 UTC, DefectivenessYT approved these changes

2020-11-15 21:44 UTC, xxdjbobbyxx commented
I will be buying a domain within the next couple of days

2020-11-15 21:45 UTC, DefectivenessYT commented
Perfect, for now though, this is fine, and make sure to commit a PR when you have changed domain.

2020-11-15 21:49 UTC, DamonOnYT requested changes
1. Listen URL is not closed properly. It is missing a " after the stream.
2. Change api_url to "external" as its on RadioSpy
3. Change Logo, Website, and find a listen url thats https.

2020-11-15 21:55 UTC, HexDevv approved these changes
> I will be buying a domain within the next couple of days

fine by me then. please fix Damon's issues then you'll be fine 👍

2020-11-15 21:59 UTC, DefectivenessYT commented
HEX U DONT EVEN WORK HERE SADUYDSAGBDS

2020-11-15 22:04 UTC, xxdjbobbyxx commented
Fixed the issues

2020-11-15 22:04 UTC, DamonOnYT approved these changes
Looks good. Got my approval.

2020-11-15 22:24 UTC, HexDevv commented
> HEX U DONT EVEN WORK HERE SADUYDSAGBDS

still open source, even so, could always hire me 😉

2020-11-15 22:25 UTC, DefectivenessYT commented
please refer to your previous issue.

2020-11-17 16:14 UTC, merged